### ISSUE TITLE
error 'cv2.cv2' has no attribute 'xfeatures2d'

### ISSUE THREAD

**Issue by jiaerwang0328** [iago-suarez/beblid-opencv-demo#1]
按照作者步骤：出现'cv2.cv2' has no attribute 'xfeatures2d'

**Comment by iago-suarez** [comment]
This is a quite common error with opencv_contrib, try uninstalling and istalling it again:

```
pip uninstall opencv-contrib-python
pip install opencv-contrib-python==4.5.1
```

**Comment by iago-suarez** [comment]
@wuranran were you able to fix the problem?

**Comment by jiaerwang0328** [comment]
yes,thanks !!

**Comment by Rizwan2613** [comment]
Hi, I'm still having the same issue on 4.5.1.48. I have checked it on later versions where `AttributeError: module 'cv2.xfeatures2d' has no attribute 'BEBLID_creat'` occures.

Any help will be appreciated.
