### ISSUE TITLE
H1to3p

### ISSUE THREAD

**Issue by gutengzczy** [iago-suarez/beblid-opencv-demo#2]
您好，请问下单应性矩阵H1to3p是怎么得到的？同样的代码我换了两张图片就一个Inlier都匹配不到了，是和H1to3p矩阵有关系吗

**Comment by iago-suarez** [comment]
@LiJianmingCSU Yes, it is related to the H1to3p matrix. If you wanna measure how well two images of a planar scene are related you have to calculate the homography relating them. You can do it very easily by clicking 4 points is each image and using [DLT](https://en.wikipedia.org/wiki/Direct_linear_transformation) to calculate the ground truth homography, see also the OpenCV function [findHomography](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga4abc2ece9fab9398f2e560d53c8c9780) where DLT is implemented. [Here](https://learnopencv.com/homography-examples-using-opencv-python-c/) you have a tutorial explaining it.

**Comment by gutengzczy** [comment]
Got it! Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iago-suarez/beblid-opencv-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 晚上6:10
收件人:&nbsp;"iago-suarez/beblid-opencv-demo"<beblid-opencv-demo@noreply.github.com&gt;;
抄送:&nbsp;"EAMO"<2436012292@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [iago-suarez/beblid-opencv-demo] H1to3p (#2)





 
@LiJianmingCSU Yes, it is related to the H1to3p matrix. If you wanna measure how well two images of a planar scene are related you have to calculate the homography relating them. You can do it very easily by clicking 4 points is each image and using DLT to calculate the ground truth homography, see also the OpenCV function findHomography where DLT is implemented. Here you have a tutorial explaining it.
