### ISSUE TITLE
Hamming instead of Euclidean distance?

### ISSUE THREAD

**Issue by pannixilin1** [iago-suarez/beblid-opencv-demo#4]
Using Hamming distance would get a best result? because BEBLID is a 512 or 256 bit binary descriptor. 

ref: 
https://medium.com/analytics-vidhya/beblid-why-feature-descriptors-are-still-important-in-2020-10f0526886f

**Comment by iago-suarez** [comment]
The answer is NO. Hamming distance is equivalent to L1 distance that is also equivalent to L2 distance if you take into account that all the have the same norm (which happens for binary descriptors, without loss of generality, when you replace zeros by -1).

My medium post is in fact using cv::NORM_HAMMING
