### ISSUE TITLE
Inliers and Inliers Ratio are 0 for any couple of images

### ISSUE THREAD

**Issue by uly94** [iago-suarez/beblid-opencv-demo#7]
The code works properly with the 2 example images graf1.png and graf3.png.
However, it doesn't work if I execute with any other images, particularly inliers and inliers ratio are always 0 and 0.0

Which is the problem? Thank you in advance

**Comment by lalithbharadwaj** [comment]
My Problem is the same as above, the code works properly with the 2 example images graf1.png and graf3.png.
However, it doesn't work if I execute with any other images, particularly inliers and inliers ratio are always 0 and 0.0.

Which is the problem? 
Thank you

**Comment by iago-suarez** [comment]
We provide ground truth only for a pair of images. 

You should replace H1to3p.xml with the ground truth homography for the pair of images that you want to evaluate.
