### ISSUE TITLE
Do not use this project

### ISSUE THREAD

**Issue by uly94** [iago-suarez/beblid-opencv-demo#8]
Project is not useful at all because it works only for the example images. If you use other 2 images to find descriptor using BEBLID the result will be always 0 and 0 meaning project doesn't work properly. Moreover author doesn't reply to your help request. I'm disappointed because I was curious about its computational speed (results are the same or a bit better than ORB results).

**Comment by iago-suarez** [comment]
That is not correct. The project works well. Which is something mandatory for any pair-reviewed journal and, of course, for have your code accept in OpenCV.

I do my best replying messages in my personal email & GitHub ( in fact I have answered you in less than 30 minutes). In general, I would recommend you not opening this kind of issues when you don't know how to use the code. 

I'm closing this issue. If you have a concrete question you can just ask it in the comments.
